// models/LeatherProduct.js
const mongoose = require("mongoose");

// Image sub-schema
const imageSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    alt: { type: String },
    type: { type: String, enum: ["main", "cover"], default: "cover" },
  },
  { _id: false }
);

// LeatherGoods Schema
const LeathersGoodsSchema = new mongoose.Schema({
  MainCategory: {
    type: String,
    enum: ["Hand Bag", "Wallet", "Card Holder", "Belt", "Briefcase", "Pounch"],
  },
  SubCategory: {
    type: String,
    enum: [
      "Tote Bag",
      "Crossbody Bag",
      "shoulder/crossbody bag",
      "Shoulder Bag",
      "Clutch",
      "Backpack",
      "Passport Holder",
      "Reversible Belt",
      "Executive Case",
    ],
  },
  Brand: { type: String },
  Model: { type: String },
  modelCode: { type: String },
  additionalTitle: { type: String },
  serialNumber: { type: String },
  sku: { type: String },
  productionYear: { type: String },
  approximateYear: { type: Boolean, default: false },
  unknownYear: { type: Boolean, default: false },
  gender: { type: String, enum: ["Men/Unisex", "Women"] },
  Material: {
    type: String,
    enum: [
      "Full-grain leather",
      "Top-grain leather",
      "Genuine leather",
      "Suede",
      "Patent leather",
      "Saffiano leather",
      "Croc-embossed",
      "Pebble leather",
      "Canvas + Leather mix",
      "Vegan Leather (PU)",
      "Leather",
      "Fabric",
    ],
  },
  interiorMaterial: {
    type: String,
    enum: [
      "Fabric",
      "Canvas",
      "Leather",
      "Suede",
      "Microfiber",
      "Textile",
      "Nylon",
      "Polyester",
      "Felt",
      "Satin",
      "Silk",
      "Cotton",
      "Wool Blend",
      "Alcantara",
    ],
  },
  Color: {
    type: String,
    enum: [
      "Black",
      "black/brown",
      "White",
      "Silver",
      "Gold",
      "Rose Gold",
      "Brown",
      "Blue",
      "Red",
      "Green",
      "Purple",
      "Pink",
      "Yellow",
      "Orange",
      "Gray",
      "Multi-color",
      "Transparent",
      "Metallic",
      "Chrome",
      "Gunmetal",
      "Beige",
    ],
  },
  hardwareColor: {
    type: String,
    enum: [
      "Gold",
      "Rose Gold",
      "Silver",
      "Platinum",
      "Chrome",
      "Gunmetal",
      "Black Metal",
      "Brass",
      "Matte Gold",
      "Matte Silver",
      "Ruthenium",
      "Palladium",
      "Antique Gold",
      "Antique Silver",
    ],
  },
  condition: {
    type: String,
    enum: [
      "Brand New",
      "Unworn / Like New",
      "Pre-Owned",
      "Excellent",
      "Not Working / For Parts",
    ],
  },
  itemCondition: {
    type: String,
    enum: ["Excellent", "Good", "Fair", "Poor / Not Working / For Parts"],
  },
  conditionNotes: { type: String },
  size: {
    width: { type: Number },
    height: { type: Number },
    depth: { type: Number },
  },
  strapLength: { type: Number },
  accessoriesAndDelivery: {
    type: [String],
    enum: [
      "Original box",
      "Dust bag",
      "Certificate of authenticity",
      "Care instructions",
      "Warranty card",
      "Gift box",
      "User manual",
      "Extra links",
      "Cleaning cloth",
      "Adjustment tools",
      "Only bag",
    ],
  },
  scopeOfDeliveryOptions: {
    type: [String],
    enum: [
      "Original packaging",
      "With papers",
      "Without papers",
      "Original box only",
      "Generic packaging",
      "Dust bag",
      "Only bag",
    ],
  },
  taxStatus: {
    type: String,
    enum: ["taxable", "shipping", "none"],
    default: "taxable",
  },
  stockQuantity: { type: Number, default: 0 },
  inStock: { type: Boolean, default: true },
  badges: {
    type: [String],
    enum: ["Popular", "New Arrivals"],
    default: [],
  },
  images: [imageSchema],
  seoTitle: { type: String },
  seoDescription: { type: String },
  seoKeywords: [{ type: String }],
  retailPrice: { type: Number },
  sellingPrice: { type: Number },
  description: { type: String },
});

// Use the existing "products" collection
module.exports = mongoose.model("LeatherProduct", LeathersGoodsSchema, "products");
